name: momenta
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - ld_impl_linux-64=2.44=h1aa0949_5
  - libexpat=2.7.1=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgomp=15.2.0=h767d61c_7
  - liblzma=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libsqlite=3.51.0=h0c1763c_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libuuid=2.41.2=he9a06e4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openssl=3.6.0=h26f9b46_0
  - pip=25.3=pyh8b19718_0
  - python=3.12.12=hd63d673_1_cpython
  - readline=8.2=h8c095d6_2
  - setuptools=80.9.0=pyhff2d567_0
  - tk=8.6.13=noxft_hd72426e_102
  - wheel=0.45.1=pyhd8ed1ab_1
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - astroplan==0.10.1
      - astropy==7.1.1
      - astropy-healpix==1.1.2
      - astropy-iers-data==0.2025.11.10.0.38.31
      - awkward==2.8.10
      - awkward-cpp==50
      - cached-property==2.0.1
      - certifi==2025.11.12
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.3.0
      - cloudpickle==3.1.2
      - contourpy==1.3.3
      - corner==2.2.3
      - crc32c==2.8
      - cryptography==46.0.3
      - cycler==0.12.1
      - cython==3.2.1
      - dask==2025.11.0
      - datetime==5.5
      - donfig==0.8.1.post1
      - fonttools==4.60.1
      - fsspec==2025.10.0
      - h5py==3.15.1
      - healpy==1.18.1
      - idna==3.11
      - igwn-auth-utils==1.4.0
      - igwn-ligolw==2.1.0
      - igwn-segments==2.1.0
      - kiwisolver==1.4.9
      - lalsuite==7.26.1
      - ligo-gracedb==2.14.3
      - ligo-skymap==2.4.1
      - locket==1.0.0
      - lscsoft-glue==4.1.1
      - matplotlib==3.10.7
      - networkx==3.5
      - numcodecs==0.16.3
      - numpy==2.3.4
      - packaging==25.0
      - pandas==2.3.3
      - partd==1.4.2
      - pillow==12.0.0
      - ptemcee==1.0.0
      - pyavm==0.9.8
      - pycparser==2.23
      - pyerfa==2.0.1.5
      - pyjwt==2.10.1
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - reproject==0.18.0
      - requests==2.32.5
      - safe-netrc==1.0.1
      - scipy==1.16.3
      - scitokens==1.8.1
      - shapely==2.1.2
      - six==1.17.0
      - toolz==1.1.0
      - tqdm==4.67.1
      - typing==3.7.4.3
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - ultranest==4.4.0
      - urllib3==2.5.0
      - zarr==3.1.3
      - zope-interface==8.1
